from __future__ import annotations

from collections.abc import AsyncIterator

from redis.commands.core import Script

class Redis:
    @classmethod
    def from_url(cls, url: str, *, decode_responses: bool = ...) -> Redis: ...
    def register_script(self, script: str) -> Script: ...
    def scan_iter(self, *, match: str = "*") -> AsyncIterator[str]: ...
    async def delete(self, *names: str | bytes | memoryview) -> object: ...
    async def ttl(self, name: str | bytes | memoryview) -> int | float | None: ...
    async def set(self, name: str | bytes | memoryview, value: object) -> object: ...
    async def get(self, name: str | bytes | memoryview) -> object: ...
    async def ping(self) -> object: ...
    async def aclose(self) -> object: ...
