from types import TracebackType
from typing import Self

class RedisContainer:
    def __init__(self, image: str | None = None, **kwargs: object) -> None: ...
    def __enter__(self) -> Self: ...
    def __exit__(
        self,
        exc_type: type[BaseException] | None,
        exc_val: BaseException | None,
        exc_tb: TracebackType | None,
    ) -> None: ...
    def start(self) -> Self: ...
    def stop(self) -> None: ...
    def get_container_host_ip(self) -> str: ...
    def get_exposed_port(self, port: int | str) -> str: ...
